// flow-typed signature: 97960f11891d379b03f33ddb909cdb12
// flow-typed version: <<STUB>>/object-path-immutable_v^1.0.1/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'object-path-immutable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'object-path-immutable' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'object-path-immutable/test' {
  declare module.exports: any
}

// Filename aliases
declare module 'object-path-immutable/index' {
  declare module.exports: $Exports<'object-path-immutable'>
}
declare module 'object-path-immutable/index.js' {
  declare module.exports: $Exports<'object-path-immutable'>
}
declare module 'object-path-immutable/test.js' {
  declare module.exports: $Exports<'object-path-immutable/test'>
}
